### ISSUE TITLE
Video file too short/fast

### ISSUE THREAD

**Issue by djeraseit** [hkang1/taiko-video#4]
Video output is too fast (even with waitFor(1000)).

Should expose option to slow down video.

**Comment by varac** [comment]
Same here, not really usable for me at the moment.

**Comment by saikrishna321** [comment]
https://github.com/hkang1/taiko-video/pull/5

**Comment by hkang1** [comment]
closing this issue with the release of [0.2.0](https://github.com/hkang1/taiko-video/releases/tag/v0.2.0) that supports custom `fps` option to be passed in when initiating a recording.

**Comment by hkang1** [comment]
closing this issue with the release of [0.2.0](https://github.com/hkang1/taiko-video/releases/tag/v0.2.0) that supports custom `fps` option to be passed in when initiating a recording.

**Comment by varac** [comment]
I'm using this example script to record a video:

```
// https://github.com/getgauge-contrib/taiko-screencast

const { openBrowser, closeBrowser, click, video } = require('taiko');

(async () => {
    try {
        await openBrowser();
        await video.startRecording('taiko-video.mp4');
        await goto('taiko.dev');
        await click('Documentation');
        await click('Plugins');
        await click('taiko-video')
    } finally {
        await video.stopRecording();
        await closeBrowser();
    }
})();
```

The resulting video is played back *much* too fast (is it just for me ?): 

https://user-images.githubusercontent.com/488213/128484179-40ce5cde-5865-43ae-8a65-796fd213286a.mp4

Please set a decent FPS as default which produces videos which compare to real life browsing, thanks !
